name: Renowned
favicon: null
layout_spectrum: 1
typography_spectrum: 0.87369
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c42b55'
    - '#ffffff'
    - '#f1d5da'
    - '#da8199'
    - '#cc5070'
  brandStrength: 0.37069939519278705
  lightness: 0.8420108715072274
  saturation: 0.551268121926114
  rhythmicContrast: 0.3461838278453797
purpose: []
